version: "3.9"

services:
   rcm_service:
    hostname: travel_recommendations  
    container_name: travel_recommendation_svc 
    build: ./
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always 
    volumes:
      - ./:/home/app
    networks:
      - default 

networks:
  default:
    driver: bridge
